version: '3'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
